"""
firstcry/session.py — FirstCry session manager

Loads cookies captured by tracker/tools/firstcry_extractor.py.

Key difference from BigBasket:
    Location is NOT baked into the session — it is passed as a `pcode`
    (pincode) query parameter per request. A single session can query
    any pincode without re-authentication.

Session file shape:
    {
        "cookies":    { name: value, ... },
        "user_agent": "Mozilla/5.0 ...",
        "_note":      "Generated by firstcry_extractor.py"
    }

Required cookies:
    FC_AUTH          — main auth token
    _$FC_UserInfo$_  — user ID
    _$FC_SID$_       — session ID

Usage:
    session = FCSession(config)
    ok = await session.start()          # loads the file
    headers, cookies = session.get_request_args()
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# Static headers observed in every FirstCry listing XHR (from HAR)
_STATIC_HEADERS: dict[str, str] = {
    "accept":           "application/json, text/javascript, */*; q=0.01",
    "accept-language":  "en-US,en;q=0.9,en-IN;q=0.8",
    "x-requested-with": "XMLHttpRequest",
    "dnt":              "1",
    # Browser context headers — required by anti-bot layer
    "origin":           "https://www.firstcry.com",
    "referer":          "https://www.firstcry.com/",
    "sec-fetch-dest":   "empty",
    "sec-fetch-mode":   "cors",
    "sec-fetch-site":   "same-origin",
}

# Cookies that must be present for the session to be considered valid
_REQUIRED_COOKIES = ("FC_AUTH", "_$FC_SID$", "_$FC_UserInfo$_")


class FCSession:
    """
    FirstCry session — loaded from firstcry_session.json.

    Stateless with respect to location: pincodes are passed per-request,
    not baked into the session. A single FCSession handles all locations.
    """

    def __init__(self, config: dict, session_file_override: str | None = None):
        fc_cfg = config.get("firstcry", {})
        sf = session_file_override or fc_cfg.get("session_file", "firstcry_session.json")
        self._session_file = Path(sf)
        self._cookies: dict[str, str] = {}
        self._user_agent: str = (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/120.0.0.0 Safari/537.36"
        )
        self.is_valid: bool = False

    async def start(self) -> bool:
        """Load session from file. Returns True if usable."""
        return self._load()

    def _load(self) -> bool:
        if not self._session_file.exists():
            logger.warning(
                "FirstCry session file not found: %s — "
                "run: python tracker/tools/firstcry_extractor.py",
                self._session_file,
            )
            self.is_valid = False
            return False

        try:
            data = json.loads(self._session_file.read_text(encoding="utf-8"))
            self._cookies = data.get("cookies", {})
            self._user_agent = data.get("user_agent", self._user_agent)

            if not self._cookies:
                logger.warning("FirstCry session file has no cookies — re-run extractor")
                self.is_valid = False
                return False

            # Check for the key auth cookie
            missing = [k for k in _REQUIRED_COOKIES if k not in self._cookies]
            if missing:
                logger.warning(
                    "FirstCry session missing cookies %s — re-run firstcry_extractor.py",
                    missing,
                )
                # Warn but don't hard-fail — FC_AUTH is most critical
                if "FC_AUTH" not in self._cookies:
                    self.is_valid = False
                    return False

            logger.info(
                "✅ FirstCry session loaded: %d cookies",
                len(self._cookies),
            )
            self.is_valid = True
            return True

        except Exception as e:
            logger.error("Failed to load FirstCry session: %s", e)
            self.is_valid = False
            return False

    def get_request_args(self) -> tuple[dict, dict]:
        """Return (headers, cookies) for use in API requests."""
        headers = {
            **_STATIC_HEADERS,
            "user-agent": self._user_agent,
        }
        return headers, dict(self._cookies)
