"""
zepto/session.py — Zepto session manager

Loads from tracker/zepto_session.json (written by zepto_extractor.py).

Key notes:
  - accessToken is short-lived (~1hr JWT).
  - refreshToken is long-lived — used to silently refresh the access token on 401.
  - Location is determined by store_id/store_ids/store_etas headers (NOT cookies).
    Each address maps to different Zepto DCs.
  - x-xsrf-token and x-csrf-secret are browser-session-level anti-CSRF tokens.

Session file shape:
    {
        "cookies": {
            "isAuth":       "true",
            "user_id":      "2e4361a9-...",
            "accessToken":  "eyJhbGciOiJIUzUxMiJ9...",
            "refreshToken": "4deb2a39-..."
        },
        "session_headers": {
            "x-xsrf-token":  "...",
            "x-csrf-secret": "...",
            "session_id":    "...",
            "device_id":     "..."
        },
        "locations": {
            "Novel Office (Marathahalli)": {
                "store_id":   "6e2378a8-...",
                "store_ids":  "6e2378a8-...,1c9e155e-...",
                "store_etas": "{\"6e2378a8-...\": 14}"
            },
            ...
        },
        "user_agent": "Mozilla/5.0 ...",
        "_note": "Generated by zepto_extractor.py"
    }
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# Cookies that must be present
_REQUIRED_COOKIES = ("isAuth", "accessToken", "refreshToken")

# Static app-level headers — hardcoded from HAR (feature flags, app version)
_APP_VERSION = "15.8.4"
_COMPATIBLE_COMPONENTS = (
    "EXTERNAL_COUPONS,BUNDLE,MULTI_SELLER_ENABLED,ROLLUPS,SCHEDULED_DELIVERY,"
    "HOMEPAGE_V2,NEW_ETA_BANNER,VERTICAL_FEED_PRODUCT_GRID,AUTOSUGGESTION_PAGE_ENABLED,"
    "AUTOSUGGESTION_PIP,AUTOSUGGESTION_AD_PIP,BOTTOM_NAV_FULL_ICON,"
    "COUPON_WIDGET_CART_REVAMP,DELIVERY_UPSELLING_WIDGET,MARKETPLACE_CATEGORY_GRID,"
    "NO_PLATFORM_CHECK_ENABLED_V2,SUPER_SAVER:1,SUPERSTORE_V1,PROMO_CASH:0,"
    "24X7_ENABLED_V1,TABBED_CAROUSEL_V2,HP_V4_FEED,WIDGET_BASED_ETA,PC_REVAMP_1,"
    "NO_COST_EMI_V1,PRE_SEARCH,ITEMISATION_ENABLED,ZEPTO_PASS:5,BACHAT_FOR_ALL,"
    "SAMPLING_UPSELL_CAMPAIGN,DISCOUNTED_ADDONS_ENABLED,UPSELL_COUPON_SS:0,"
    "ENABLE_FLOATING_CART_BUTTON,FASHION_REVAMP,WIDGET_RESTRUCTURE,MULTITAB_V2,"
    "NEW_ROLLUPS_ENABLED,SEARCH_PRODUCT_GRID_V2,PLP_ON_SEARCH,SEARCH_FILTERS_V1,"
    "DYNAMIC_FILTERS"
)

_STATIC_APP_HEADERS: dict[str, str] = {
    "app_sub_platform":   "WEB",
    "app_version":        _APP_VERSION,
    "appversion":         _APP_VERSION,
    "platform":           "WEB",
    "tenant":             "ZEPTO",
    "source":             "DIRECT",
    "marketplace_type":   "SUPER_SAVER",
    "auth_from_cookie":   "true",
    "auth_revamp_flow":   "v2",
    "compatible_components": _COMPATIBLE_COMPONENTS,
    "x-without-bearer":   "true",
    # Standard browser context
    "accept":             "application/json, text/plain, */*",
    "accept-language":    "en-US,en;q=0.9,en-IN;q=0.8",
    "cache-control":      "no-cache",
    "pragma":             "no-cache",
    "priority":           "u=1, i",
    "dnt":                "1",
    "origin":             "https://www.zepto.com",
    "referer":            "https://www.zepto.com/",
    "sec-ch-ua":          '"Microsoft Edge";v="147", "Not.A/Brand";v="8", "Chromium";v="147"',
    "sec-ch-ua-mobile":   "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-fetch-dest":     "empty",
    "sec-fetch-mode":     "cors",
    "sec-fetch-site":     "same-site",
    "content-type":       "application/json",
}


class ZeptoSession:
    """
    Zepto session loaded from zepto_session.json.

    Provides per-location request headers (store_id etc.) to the API client.
    Attempts access token refresh on 401 via the refreshToken cookie.
    """

    def __init__(self, config: dict, session_file_override: str | None = None):
        z_cfg = config.get("zepto", {})
        sf = session_file_override or z_cfg.get("session_file", "zepto_session.json")
        self._session_file = Path(sf)

        self._cookies: dict[str, str] = {}
        self._session_headers: dict[str, str] = {}
        self._locations: dict[str, dict] = {}   # name → {store_id, store_ids, store_etas}
        self._user_agent: str = (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/147.0.0.0 Safari/537.36 Edg/147.0.0.0"
        )
        self.is_valid: bool = False

    async def start(self) -> bool:
        return self._load()

    def _load(self) -> bool:
        if not self._session_file.exists():
            logger.warning(
                "Zepto session file not found: %s — "
                "run: python tracker/tools/zepto_extractor.py",
                self._session_file,
            )
            self.is_valid = False
            return False

        try:
            data = json.loads(self._session_file.read_text(encoding="utf-8"))
            self._cookies       = data.get("cookies", {})
            self._session_headers = data.get("session_headers", {})
            self._locations     = data.get("locations", {})
            self._user_agent    = data.get("user_agent", self._user_agent)

            if not self._cookies:
                logger.warning("Zepto session has no cookies — re-run zepto_extractor.py")
                self.is_valid = False
                return False

            missing = [k for k in _REQUIRED_COOKIES if k not in self._cookies]
            if missing:
                logger.warning(
                    "Zepto session missing cookies %s — re-run zepto_extractor.py", missing
                )
                if "accessToken" not in self._cookies:
                    self.is_valid = False
                    return False

            if not self._locations:
                logger.warning("Zepto session has no locations — re-run zepto_extractor.py")
                self.is_valid = False
                return False

            logger.info(
                "✅ Zepto session loaded: %d cookies, %d location(s): %s",
                len(self._cookies),
                len(self._locations),
                list(self._locations.keys()),
            )
            self.is_valid = True
            return True

        except Exception as e:
            logger.error("Failed to load Zepto session: %s", e)
            self.is_valid = False
            return False

    def get_location_names(self) -> list[str]:
        return list(self._locations.keys())

    def get_request_args(self, location_name: str) -> tuple[dict, dict]:
        """
        Return (headers, cookies) for the given location.
        Headers include all static app headers + session headers + store headers.
        """
        loc = self._locations.get(location_name, {})
        store_id   = loc.get("store_id", "")
        store_ids  = loc.get("store_ids", store_id)
        store_etas = loc.get("store_etas", "{}")

        session_id = self._session_headers.get("session_id", "")
        device_id  = self._session_headers.get("device_id", "")

        headers = {
            **_STATIC_APP_HEADERS,
            "user-agent":    self._user_agent,
            # Session-level tokens
            "x-xsrf-token":  self._session_headers.get("x-xsrf-token", ""),
            "x-csrf-secret": self._session_headers.get("x-csrf-secret", ""),
            "session_id":    session_id,
            "sessionid":     session_id,
            "device_id":     device_id,
            "deviceid":      device_id,
            # Location-specific headers
            "store_id":      store_id,
            "storeid":       store_id,
            "store_ids":     store_ids,
            "store_etas":    store_etas,
        }

        if not store_id:
            logger.warning(
                "Zepto: no store_id found for location '%s'. "
                "Re-run zepto_extractor.py to capture store data.",
                location_name,
            )

        return headers, dict(self._cookies)

    def update_access_token(self, new_token: str) -> None:
        """Update the in-memory access token after a refresh."""
        self._cookies["accessToken"] = new_token
        # Persist to disk so next startup doesn't need immediate refresh
        try:
            data = json.loads(self._session_file.read_text(encoding="utf-8"))
            data["cookies"]["accessToken"] = new_token
            self._session_file.write_text(
                json.dumps(data, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )
        except Exception as e:
            logger.debug("Could not persist refreshed accessToken: %s", e)

    def get_refresh_token(self) -> str:
        return self._cookies.get("refreshToken", "")
