"""
bigbasket_extractor.py — BigBasket session extractor

Opens BigBasket in a real browser, lets you log in and set your address,
then captures cookies and saves to the specified session file.

Usage:
    python tracker/tools/bigbasket_extractor.py
    python tracker/tools/bigbasket_extractor.py --session-file bigbasket_tumakuru_session.json

For each delivery address you want to track, run with a different --session-file
then add it to config.yaml → bigbasket.locations.
    2. You log in and navigate normally (select delivery address)
    3. When you close the browser (or press Enter in terminal), it:
       - Extracts all cookies
       - Saves to tracker/bigbasket_session.json
    4. The tracker reads this file at startup

Session validity:
    BigBasket sessions are long-lived (weeks) as long as cookies are active.
    Re-run this script if you see "session expired" alerts.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from pathlib import Path

# ── Path setup ──────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent   # tracker/
sys.path.insert(0, str(BASE_DIR))

SESSION_FILE = BASE_DIR / "bigbasket_session.json"
PROFILE_DIR  = BASE_DIR / "browser_profile" / "bigbasket"


async def main(auto: bool = False) -> None:
    try:
        from playwright.async_api import async_playwright
    except ImportError:
        print("❌ Playwright not installed. Run: pip install playwright")
        print("   Then: playwright install chromium")
        sys.exit(1)

    print("=" * 60)
    print("  BigBasket Session Extractor")
    print("=" * 60)
    print()
    print("📌 Steps:")
    print("  1. A Chrome window will open")
    print("  2. Log into BigBasket (if not already)")
    print("  3. Make sure your delivery address is selected")
    print("  4. Browse a little — search 'hot wheels' if you like")
    print("  5. Close the browser window when done")
    print()

    PROFILE_DIR.mkdir(parents=True, exist_ok=True)

    async with async_playwright() as p:
        browser = await p.chromium.launch_persistent_context(
            user_data_dir=str(PROFILE_DIR),
            headless=False,
            viewport={"width": 1280, "height": 800},
            args=["--disable-blink-features=AutomationControlled"],
        )

        page = browser.pages[0] if browser.pages else await browser.new_page()

        print("🌐 Navigating to BigBasket...")
        await page.goto("https://www.bigbasket.com", wait_until="domcontentloaded")

        print()
        print("✅ Browser is open. Log in, select your address, browse normally.")
        print("   Search 'hot wheels' in BigBasket so the session bakes in.")
        print()
        print("    >>> When you're done, press ENTER HERE (in this terminal) <<<")
        print()

        if auto:
            print("  👉 Auto mode — waiting 10s for page to settle...")
            await page.wait_for_timeout(10000)
        else:
            # Wait for user to signal done — keeps browser alive for cookie capture
            loop = asyncio.get_event_loop()
            await loop.run_in_executor(None, input, "")

        print("🍪 Extracting session data...")

        try:
            # Capture all cookies (no URL filter — gets everything inc. domain cookies)
            cookies_list = await browser.cookies()
        except Exception:
            cookies_list = []

        await browser.close()

        cookies: dict[str, str] = {c["name"]: c["value"] for c in cookies_list}

        if not cookies.get("sessionid"):
            print()
            print("⚠️  Warning: 'sessionid' not found — you may not be logged in.")
            print("   Re-run the extractor and log in before closing.")

        # Extract nhid for display
        nhid = cookies.get("_bb_nhid", "unknown")

        session_data = {
            "cookies": cookies,
            "user_agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/120.0.0.0 Safari/537.36"
            ),
            "nhid": nhid,
            "_note": "Generated by bigbasket_extractor.py — do not edit manually",
        }

        SESSION_FILE.write_text(
            json.dumps(session_data, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )

        print()
        print(f"✅ Session saved → {SESSION_FILE}")
        print(f"   Cookies captured: {len(cookies)}")
        print(f"   Hub ID (_bb_nhid): {nhid}")
        print()
        print("You can now run:")
        print("  python tracker/main.py --once")
        print()


if __name__ == "__main__":
    args = argparse.ArgumentParser(description="BigBasket session extractor")
    args.add_argument(
        "--session-file",
        default="bigbasket_session.json",
        help="Session file name (default: bigbasket_session.json). "
             "Use a different name per delivery address.",
    )
    args.add_argument("--auto", action="store_true", help="Auto-refresh (no manual inputs)")
    parsed = args.parse_args()
    # Override global SESSION_FILE from CLI
    SESSION_FILE = BASE_DIR / parsed.session_file

    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
    asyncio.run(main(auto=parsed.auto))
