"""
firstcry_extractor.py — FirstCry session extractor

Opens FirstCry in a real browser, lets you log in and set your delivery address,
then captures cookies and saves to tracker/firstcry_session.json.

Usage:
    python tracker/tools/firstcry_extractor.py

Unlike BigBasket, you only need to run this ONCE — the single session file
is used for ALL pincode locations (pincodes are passed per-request, not
baked into the session).

Steps:
    1. A Chrome window opens → https://www.firstcry.com
    2. Log in (if not already)
    3. Set any delivery address (pincode will be overridden per-request)
    4. Browse — search "hot wheels" to warm up the session
    5. Press ENTER in this terminal when done

Session validity:
    FirstCry sessions are long-lived. Re-run if you see auth errors.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path

# ── Path setup ──────────────────────────────────────────────────────
BASE_DIR     = Path(__file__).resolve().parent.parent   # tracker/
SESSION_FILE = BASE_DIR / "firstcry_session.json"
PROFILE_DIR  = BASE_DIR / "browser_profile" / "firstcry"


async def main(auto: bool = False) -> None:
    try:
        from playwright.async_api import async_playwright
    except ImportError:
        print("❌ Playwright not installed. Run: pip install playwright")
        print("   Then: playwright install chromium")
        sys.exit(1)

    print("=" * 60)
    print("  FirstCry Session Extractor")
    print("=" * 60)
    print()
    print("📌 Steps:")
    print("  1. A Chrome window will open")
    print("  2. Log into FirstCry (if not already)")
    print("  3. Set a delivery address (any — pincodes override per request)")
    print("  4. Search 'hot wheels' to warm up the session")
    print("  5. Close the browser, or press ENTER here when ready")
    print()
    if not auto:
        print("  NOTE: You only need ONE session file for all pincodes.")
        print()

    PROFILE_DIR.mkdir(parents=True, exist_ok=True)

    async with async_playwright() as p:
        browser = await p.chromium.launch_persistent_context(
            user_data_dir=str(PROFILE_DIR),
            headless=False,
            viewport={"width": 1280, "height": 800},
            args=["--disable-blink-features=AutomationControlled"],
        )

        page = browser.pages[0] if browser.pages else await browser.new_page()

        print("🌐 Navigating to FirstCry...")
        await page.goto("https://www.firstcry.com", wait_until="domcontentloaded")

        print()
        print("✅ Browser is open. Log in, set your address, browse normally.")
        print("   Search 'hot wheels' on FirstCry so the session is active.")
        print()
        print("    >>> Press ENTER HERE (in this terminal) when done <<<")
        print()

        if auto:
            print("  👉 Auto mode — waiting 10s for page to settle...")
            await page.wait_for_timeout(10000)
        else:
            loop = asyncio.get_event_loop()
            await loop.run_in_executor(None, input, "")

        print("🍪 Extracting session data...")

        try:
            cookies_list = await browser.cookies()
        except Exception:
            cookies_list = []

        await browser.close()

    cookies: dict[str, str] = {c["name"]: c["value"] for c in cookies_list}

    # Validate the most critical cookies
    missing = []
    for key in ("FC_AUTH", "_$FC_SID$", "_$FC_UserInfo$_"):
        if key not in cookies:
            missing.append(key)

    if missing:
        print()
        print(f"⚠️  Warning: missing cookies: {missing}")
        print("   Make sure you are logged in before pressing ENTER.")
        print("   Re-run the extractor and log in first.")

    # Show globalPincode for info
    pincode = cookies.get("globalPincode", "not found")
    user_id = cookies.get("_$FC_UserInfo$_", "unknown")

    session_data = {
        "cookies":    cookies,
        "user_agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/120.0.0.0 Safari/537.36"
        ),
        "_note": "Generated by firstcry_extractor.py — do not edit manually",
    }

    SESSION_FILE.write_text(
        json.dumps(session_data, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    print()
    print(f"✅ Session saved → {SESSION_FILE}")
    print(f"   Cookies captured : {len(cookies)}")
    print(f"   User ID          : {user_id}")
    print(f"   Global pincode   : {pincode}")
    print()
    print("Next steps:")
    print("  1. Edit tracker/config.yaml → firstcry.enabled: true")
    print("  2. Add your pincodes under firstcry.locations")
    print("  3. Run: python tracker/main.py --once")
    print()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--auto", action="store_true", help="Auto-refresh (no manual inputs)")
    args = parser.parse_args()

    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
    asyncio.run(main(auto=args.auto))
